name: Build and Test

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v1
        with:
          node-version: 24

      - run: npm ci
      - run: npm test
      - run: npm run build
      - run: npm run openapi
